version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: yarn
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      KSA1nMYymskY4tL6NDROAvwrrU+rX6sjI9jJJIAgOnzX6/JrdnvS3VoJRfY7huSFr/KoV35eartzcmTysbUIr/WiDIJWSzsXDkBviD+7AWXZu8kPKyUEpZKexG6TYegZqOSgGFh8TcmKmDnb44G2oTs8dehS2KQbW4xa1ahEJ5ic/cCtjvuafUQmvHiaYWSLorP/4N8id4lR3iatsLK2yLaw+CL7tT+uwLQOFh2ddksS2WvpeXRt8d83pE4y0eRWyiQQ2gQzwytbp4v1u/lM0NjMmsBaWCBmj2KYiSNrQH96nSXxESrGML1TNyhpoaXxArSQ/dhtdBSguth27JHNuBrx0pyEv1ONkhvjbLt6QMgLPNvU8yDmGQDkOrlIw6YSb2L3f2KtzP9SXiU2nvXa5qJgI6Ml2Ry+2uGMsznizuFX6LAYadXRJ2J0LwoslZZFjUv5wwq1rgSoRL/PEkYBCtgROaFumP67hHEAPJpXqSU5+X8LYZd7IyGH5Dz/Q/ZsqVsdY5JHu+7nJIP5o/EfzSZwkuJPILacPzYVQN+79eqyvDGc25g2NbxY+nnfMxoCJCQjVt624Dp7D0ODlp2YFSXwalXof9+KGQ2czsQUDxY60+/n8eErNOqkRvxZY2p1Hn94TZR0gMjjKItD7/25OmCiaLmutsfFdjddMS26fxQ=
