version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      hZXxSA10bQLMia2xaN9apqgJ4ruAUXj+EW5FoDXCeNn1nXkyJxUrrJ8MY+7sjhmWgf2n311SqN/y6Tdp/QatUFBsLRoXXCEHM1MioqZOIcVaZYkpZwqemYWVbbZLx0y616ecEZWTZCt1a/k/xrAxBNmApfZSQ4PKMnNpRk3IutVdLSD4lqMllRUhKryeeH1fe6th0hCg760OnO+VtAoR9XFoYAVWyEhLiJaDntQkqqfzuSWKnci/KBL1V8H1QDQd0tlozOlIQIxmu5FAszwaToi9F2SUxpPnTRp1sJ78Uu+U93vuNTJEtCsUkhdkIwlbKElbZ2lbWX1zO9Sr0ZFH2wwFO8NgKZywzEPMy6WP6bBAh8R5XS1xrfi9hcHd5kZowmZQAhMmWChyxywUj42T7gT8dXm4CFcc5xWF2WMQbCRr4v53nsFFx7IwMm+A6QReBv3gTqAct8lgYrdqnChP+/pIqsN6x4jed8RTOdjPlg+4v8+aF2mGj5Cgbsu/Ibwe+iAEct4G8d1LjrFDOVLVRnYEBF3ir3JGdh1kcsF/llDt8sW7r/CdK+eZ8COOdD3cn1yn6+sF/Wk+gVIzZOcxa2ZehNEtARsivNR89EAoYLMlWDQsD0SPVZrTgLNjp+J6kPT/SWkYphEBq+J/JyuqXm1+4x4A+M0V3Z6fv7EFOy8=
