version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      ItKWPGVvEl6fMGgrHmKUoQcivn9Y01h348a43ljmanqP6HVgP/8XvjeD65TlOk4YgwWlNOIFQicV5H37WXl5PTPcsOb8RQPOJf5U++qbT4OImFfjsMvoNymSnVTKpdWPCWnxC7FW4TVQuzrdguC3jrECTcqkzSpe3bZfych4JUxZQGtxqi0+I9oFyxcRwB8ZIJ/d9VCWlhSgM5XNVEZUNvBuxUFzLsvXh9T56V1OpwIyzEzopBMbsohUP7CzKmmKrDsIxlPk+iR1fc1nUInXcXviTb5Mc+DVJ+fj0G+77LQ6wi4TTdYHfuaiB93F5Lrkid5i80ePq21C+/508ANQAxREB8rQI8qLpraJvQ1FXxZIlmCTIkDNxjxv2TULHPuJwyvaM5YpWxdy6YEdW1wXPKVv5b3mRra1UpsSHE5SpDIFsU1j0ZWkjX0p6uuPfRdJntdBMFu/l0JmmKzWBB2BJsQYN2qPAes/xlIm61bAR7KVCyCgxCCccYU8xWZwV/lEMzovh/z8WaYje0VujO13upsk45diDQEjjWeiokL77FkT2dmwsGTPlBehKOLjapRoawIZt4seJk8aZOTtAfTF1fHPDPnsdWCo+IRVZtHSlg8WCf/ed8k0uQNEU1cPZ8fGEHOIgElHken4UOhYYcK9r+P/IswBAGfSBKpoq8m3Zmg=
