version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '13'
  - '14'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/surge.bash)"
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/9fa2fa025c77b463d03154f39922af95cadc9c67/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      bT5p6shfSnGCvkU4K4KKQEnYyh53YKGfuxZjm3STsodUqOcG89m5RYcxHrDU2+4P4uxvg1dsirjqvJRDCdfxmZ8dzYwj97r1sLAAx/csnUEdJBIlOUxQZm9DXSJ8tuFSC/ozq5zu5T0aDlyJYYrR3+dnrZdk8ZXEjyungb6IJlk1w0sdMaUWTw84dEactadiZdHzGUJ+Ng9Z7zr44CRmjgIjacQymWvQoxoJkMAEkbx7iCRBkz7/cWkxRoaAb5w2woJBS2eIoHTL2gwsvaengbAqkqa6ad3fpfYmhwspEK+bpqbkV6Dg7qYrU5b5fnJblVhGz4G5hF7pn0kmD0ZtKtONgmEVmYdjXyE7qAqcBrknmvCrBBR6cvP6JMWiiGF7IM3fhEcmYk35/b6Z1f5J9m3XrMtBGCqYsLZZ0p6wdrTTLDOW5f/aY7PrmTI5gYxXuKi1EIdE18CgB8wYEMo/FgxH6odh29EDKJFQvPtuAWcZlsROnvnnBJt69KQEtvIQoSUgQjoD+3q9vRxUbA3rb1+fUs4AQm0AOSW27E1iFzmgDu0c58K/6Zt61gsi69QfH4NlHviX7fC9Ilb4waIs5daM2StVfFgYYF29OfFgmVuVxGVq2r3suSMivGypdEDTEySeoVmLmRGsQ/BMCbKxUWp0FtugsnVt3UWN1wpqu3k=
